sudo: false
language: node_js
node_js:
- 0.1
install:
- npm install
before_script:
- npm install -g grunt-cli
script:
- grunt travis
addons:
  sauce_connect: true
env:
  global:
  - secure: hbYwPAUXxASydsTYqHEgmeaNuMf6JB64dZ+i91g45sef7BMqw9pB6OPmV9pynNj2NeyKNfk7UN+fSyAf3GqDWJ047//tjjuC8klzBLhaPg5gPKqV9iKWqdHaksZ6a/rEcRcWeo6JZLpNFBFQC8aedJrhthBzl3HZ+4Mt7er3Waq5k5MlaSA0azdO/cuz/CfslPw35q6nCbEk+2SmsT9QjdJp2pluXaWI4wFlXAJROmOObiFIsmZxEPUaMfmU+2bOQ7kQV2EK3jzr1kN9w/muhx2G5KH1CUAlH8Ae1j4vit4nqGEAQdmif9e8Lgx9XafavAEaoA96PgoT+8sx2Yep3a/QrCVmc7/D/BgN3ltHTydeUPhAxLWoBekhBYaZUxIRofP7L6AUTtTwBQY3yCZ0qgsekYtS+dd9uSPY5QjxorKvtasUz9HzHMdh/dv4HczeVGPgAxdi9VIcPpKFfbClr3VHIFCA/FhAGGiALuLfQaJ7H1MU/kDgWl7Ikb3LP/1OAg8Uo5s99eUKLtaqhUoOCIbGW6ugcJ/k6bpl14iDNyGg3y0eFJPwR53kgl+2A3GMD4Yjiv5PF34nqcqr8840di9/Mvu6N1yC9hr6A+gnhb8EHAUcMbibOiglT2bHIknCafKCdMCz6XBNhcdLemvzcgBFG2BtWuSX6/c23cGI4/4=
  - secure: eeQsV2U0Smlf10Yj87RFUGCeurqggFNHm50qh07vf8juD4VCdBx2u96U5g4AceLmlJNyvRB2ejaadNcrel+tueGJjIsx1hIKi3Hd0klHsIcriIvyH1x2lJGJtTmv9QejqzYZndMttgxD9UhB4rQOpe3Z+zEkPsEKg7LMUJgHNLS65eHte6kP+Mj2borXNrhuUwbko1uH57iiHGguHWFICl2zE8PFPBgLMtF6tO128hbHN3i1jxflVbyMMcyHAAmLxb2usPi0+fI/7Y6yrZQJjAXtb0njdvwJ3xPBCrg0Ts0bupmypn3TkDA5mJ0o7CY3M6pCHEl9bbRRp6efGG5mjzVCSl5jbICViHUa6KWya6hg9WWZli3UFq/56Xk9fKPCy2z913OPedeWyWJth7BZ9t1/CjtJtZiAzVLkooLydoc348PtCc72RgxhihBvwfB958hFzLU1Lrta225OvyNNF6X5oBKHZPI48Onm1Rjqwj7qmwLymgXgrXkpCCAP+gUhAHEsDdgPQb3SRqrNwGdAAULLz8SWu5uLYRaUUModcQrYpPI79ULqypiy9zoF/tjsGE5HTMDo8Tat9cjgJWl4vgIkXjhWfKDxTLiusTyehyQoEx4eybuyZvZkgSKFnQMjyJMHINCL1KoVfC55cPBRBsMHntyMDwkJHvUizWTWdJ4=
notifications:
  email:
    on_success: always
    on_failure: always
