sudo: false
language: node_js
node_js:
  - 0.10
install:
  - npm install
before_script:
  - npm install -g grunt-cli
script:
  - grunt

notifications:
  email:
    on_success: always
    on_failure: always